#!/bin/bash

initUsers=$(cut -d: -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d: -f1)
iter=0

for user in $initUsers
do
Users[$iter]=$user
Users2[$iter]=$user
iter=$iter+1
done

#echo ${Users[@]}



iter=0


echo "Please enter the names of the users (be exact)"
read input


for usr in $input
do
Input[$iter]=$usr
iter=$iter+1
done
#echo ${Input[@]}
y=${#Users[@]}
u=${#Input[@]}



for ((i = 0; i < $u; i++)); do
  for ((j = 0; j < $y; j++)); do
uvar=${Users[$j]}
ivar=${Input[$i]}
   
if [[ "$uvar" == "$ivar" ]];
then 
#echo "yes $uvar $ivar" 
Users2[$j]=""

fi

  done
done

echo "Examine the following users:"
echo ${Users2[@]}


