#!/bin/bash

hans=$(cut -d: -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d: -f1)
yertt=0

for word in $hans
do
Test[$yertt]=$word
yertt+=1
done

echo ${Test[@]}



yertt=0


echo "Please enter the names of the users (be exact)"
read bumb


for wordi in $bumb
do
Yeng[$yertt]=$wordi
yertt+=1
done


echo ${Yeng[@]}



