#!/bin/bash

initUsers=$(cut -d: -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d: -f1)
iter=0

for user in $initUsers
do
Users[$iter]=$user
iter=$iter+1
done

stuff=$(grep -Po '^sudo.+:\K.*$' /etc/group)
iter=0

for admin in $stuff
do
Admins[$iter]=$admin
iter=$iter+1
done

echo "Please enter the names of the admins (be exact)"
read input

iter=0
for usr in $input
do
Input[$iter]=$usr
iter=$iter+1
done

u=${#Input[@]}
y=${#Admins[@]}

for ((i = 0; i < $u; i++)); do
  for ((j = 0; j < $y; j++)); do
ivar=${Input[$i]}
avar=${Admins[$j]}
   
if [[ "$avar" == "$ivar" ]];
then 
echo "yes $avar $ivar" 

else [[ "$avar" != "$ivar" ]]; 
echo "No $avar $ivar" 
unset ${Input[$i]} 
fi

  done
done

echo "Please enter the names of the users (be exact)"
read input

iter=0
for usr in $input
do
Input[$iter]=$usr
iter=$iter+1
done

u=${#Input[@]}
y=${#Users[@]}

for ((i = 0; i < $u; i++)); do
  for ((j = 0; j < $y; j++)); do
ivar=${Input[$i]}
uvar=${Users[$j]}
   
if [[ "$uvar" == "$ivar" ]];
then 
echo "yes $uvar $ivar" 

else [[ "$uvar" != "$ivar" ]]; 
echo "No $uvar $ivar" 
unset ${Input[$i]} 
fi

  done
done




